Import("env")

qrccpp = env.Qrc4("Karaoke")
src_files = Split("""
            main.cpp
            GuiManager.cpp
            Karaoke.cpp
            login/Login.cpp
            search/SearchResult.cpp
            songlist/SongListView.cpp
            singerlist/SingerList.cpp
            player/player.cpp
            background/Background.cpp
            ../database/database.cpp
            ../database/sqlite3.c
            ../log/log.cpp
            ../cli/cli.cpp
            ../ipc/ipc.cpp
            ../ptasking/ptasking.cpp
            widget/keyboard.cpp
            widget/inputline.cpp
            """)

webkara = env.Program('webkara',src_files+qrccpp)
env.Install("#build", webkara)